// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import ContactForm from './ContactForm/index.svelte';
import ContentLister from './ContentLister/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import RichText from './RichText/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	biography: Biography,
	contact_form: ContactForm,
	content_lister: ContentLister,
	experience: Experience,
	hero: Hero,
	image_block: ImageBlock,
	rich_text: RichText,
	tech_list: TechList
};
